Site_resa/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reservation.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_user', views.login_user, name="login"),
    path('logout_user', views.logout_user, name='logout'), 
    path('register_user', views.register_user, name='register'), 
]

members/models.py
from django.db import models

# Create your models here.

members/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import Select


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50, label='Prénom', widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=50, label='Nom', widget=forms.TextInput(attrs={'class':'form-control'}))
    LANGUE_CHOICES = [
    ('FR', 'Français'),
    ('NL', 'Néerlandais'),
    ('EN', 'Anglais'),
    ('DE', 'Allemand'),
    ('AR', 'Arabe'),
]

    langue = forms.ChoiceField(choices=LANGUE_CHOICES, widget=Select(attrs={'class':'form-control'}))


    class Meta:
        model= User
        fields = ('username', 'first_name', 'last_name', 'email', 'langue', 'password1', 'password2' )

    def __init__(self, *args, **kwargs): 
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['langue'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].label = 'Mot de passe'
        self.fields['password2'].label = 'Confirmation du mot de passe'
    

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

from .forms import RegisterUserForm

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ("Success"))
            return redirect('home')
        else:
            messages.success(request, ("I l y a une erreur, reessayer..."))
            return redirect('login')
    else:
        return render(request, 'authenticate/login.html', {})
    
def logout_user(request):
    logout(request)
    messages.success(request, ("Vous etes deconnecte!"))
    return redirect('home')

def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Inscription reussi"))
            return redirect('home')
        else:
            messages.success(request,'Invalid form')
    else:
        form = RegisterUserForm()

    return render(request, 'authenticate/register_user.html', {
        'form':form,
    })

members/templates/authenticate/login.html
{% extends 'base.html' %}
{% block title %}NYGMA - Login{% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-lg-6 shadow p-4">
                <h3 class="text-center">Connexion</h3>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="inputEmail1">Login</label>
                        <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword1">Mot de passe</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                    <div class="form-group text-center">
                      <button type="submit" class="btn btn-primary">Se connecter</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

members/templates/authenticate/register_user.html
{% extends "base.html" %}
{% block title %}NYGMA - Register{% endblock %}
{% block content %}
{% if form.errors %}
  <div class="alert alert-warning alert-dismissible fade show m-3" role="alert">
    Il y a eu une erreur lors de la soumission
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-lg-6 shadow p-4">
                <h3 class="text-center">Inscription</h3>
                <form action="{% url 'register' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Nom d'utilisateur</label>
                        <input type="text" class="form-control" id="id_username" name="username" placeholder="Entrez votre nom d'utilisateur" required>
                        {% if form.username.errors %}
                            <small class="form-text text-danger">{{ form.username.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_first_name">Prénom</label>
                        <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Entrez votre prénom" required>
                        {% if form.first_name.errors %}
                            <small class="form-text text-danger">{{ form.first_name.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_last_name">Nom</label>
                        <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Entrez votre nom" required>
                        {% if form.last_name.errors %}
                            <small class="form-text text-danger">{{ form.last_name.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input type="email" class="form-control" id="id_email" name="email" placeholder="Entrez votre email" required>
                        {% if form.email.errors %}
                            <small class="form-text text-danger">{{ form.email.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_langue">Langue</label>
                        {{ form.langue }}
                        {% if form.langue.errors %}
                            <small class="form-text text-danger">{{ form.langue.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_password1">Mot de passe</label>
                        <input type="password" class="form-control" id="id_password1" name="password1" placeholder="Entrez votre mot de passe" required>
                        {% if form.password1.errors %}
                            <small class="form-text text-danger">{{ form.password1.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_password2">Confirmation du mot de passe</label>
                        <input type="password" class="form-control" id="id_password2" name="password2" placeholder="Confirmez votre mot de passe" required>
                        {% if form.password2.errors %}
                        <small class="form-text text-danger">{{ form.password2.errors.0 }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group text-center">
                      <input type="submit" value="S'inscrire" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}