Site_resa/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reservation.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_user', views.login_user, name="login"),
    path('logout_user', views.logout_user, name='logout'), 
    path('register_user', views.register_user, name='register'), 
]

reservation/urls.py
from django import views
from django.urls import path
from .views import *
from . import views



urlpatterns = [
    path('',home, name="home"),
    path('addshow',addshow, name="addshow"),
    path('all_shows', allShows , name="allShows"),
    path('show/<int:show_id>', displayShow , name="show_detail" ),
    path('updateShow/<int:show_id>', updateShow, name='updateShow'),
    path('deleteShow/<int:show_id>', deleteShow, name="deleteShow"), 
    path('shows/<int:show_id>/review', views.create_review, name='create_review'),

    path('artist', allArtists , name="allArtists"),   
    path('artist/<int:artist_id>',showArtist, name='showArtist'), 
    path('artist/create/', artistCreate, name='artistCreate'),  
    path('artist/<int:artist_id>/edit', editArtist , name='artist_edit'), 
    path('artist/<int:artist_id>/delete', deleteArtist, name='deleteArtist'), 
    
    path('type/',  show_all_type , name='type_show'),
    path('type/<int:type_id>', showType, name='type_detail'),

    path('locality/', allLocality, name='locality_index'),
    path('locality/<int:locality_id>', showLocality, name='locality_show'),

    path('myaccount/', displayUserAccount, name='myaccount' ),

    path('search_shows/', search_shows, name='search_shows' ),


    path('representation/create', createRepresentation, name='createRepresentation'),
    path('representation/<int:show_id>/reserver', representationReserver , name='representationReserver'),
    path('representation/<int:representation_id>/user_reservation', representationUserReservation , name='representationUserReservation'),
    path('reservation/<int:pk>/update/', ReservationUpdateView.as_view(), name='update_reservation'),

    path('payment/', payment, name='payment'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session' ),
    path('panier/', ProductLandingPageView.as_view(), name= 'landing-page'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    
    #path('role/', views.role.index, name='role_index'),
    #path('role/<int:role_id>', views.role.show, name='role_show'),
    #path('location/', views.location.index, name='location_index'),
    #path('location/<int:location_id>', views.location.show, name='location_show'),
    #path('show/', views.show_detail.index, name='show_index'),
    #path('show/<int:show_id>', views.show_detail.show, name='show_show'),
    #path('representation/', views.representation.index, name='representation_index'),
    #path('representation/<int:representation_id>', views.representation.show, name='representation_show'),


]

reservation/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Locality(models.Model):
    postal_code = models.IntegerField(max_length=6)
    locality = models.CharField(max_length=60)
    
    def __str__(self):
        return self.locality


class Location(models.Model):
    slug = models.CharField(max_length=60, unique=True)
    designation = models.CharField(max_length=60)
    address = models.CharField(max_length=255)
    locality_id = models.ForeignKey(Locality, blank=True, null=True, on_delete=models.SET_NULL, related_name='locations')
    website = models.CharField(max_length=255)
    phone = models.CharField(max_length=30)

    def __str__(self):
        return self.designation


class Show(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.CharField(max_length=60, blank=True, null=True)
    title = models.CharField('Show Title', max_length=255, blank=True, null=True)
    description = models.TextField('Show Description', blank=True, null=True)
    poster_url = models.CharField('Show Image', max_length=255, blank=True, null=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    location_id = models.ForeignKey(Location, blank=True, null=True, on_delete=models.SET_NULL)
    bookable = models.BooleanField(blank=True, null=True)
    price = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    representations = models.ManyToManyField('Representation', blank=True)
    
    def get_representations(self):
        return self.representations.all()

    def __str__(self):
        return self.title
    
    def get_display_price(self):
        return "{0:.2f}".format(self.price)


class Type(models.Model):
    type = models.CharField(max_length=60)

    def __str__(self):
        return self.type


class Artist(models.Model):
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)
    types = models.ManyToManyField(Type, through='ArtisteType')

    def __str__(self):
        return f'{self.firstname} {self.lastname}'



class ArtisteType(models.Model):
    artist_id = models.ForeignKey(Artist, blank=True, null=True, on_delete=models.CASCADE)
    type_id = models.ForeignKey(Type, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        db_table = "artist_type"
        
    def __str__(self):
        artist_str = str(self.artist_id) if self.artist_id else ''
        type_str = str(self.type_id) if self.type_id else ''
        return artist_str + ' ' + type_str



class ArtistTypeShow(models.Model):
    artiste_type_id = models.ForeignKey(ArtisteType, blank=True, null=True, on_delete=models.CASCADE)
    show_id = models.ForeignKey(Show, blank=True, null=True, on_delete=models.CASCADE)


class Representation(models.Model):
    show_id = models.ForeignKey(Show, blank=True, null=True, on_delete=models.CASCADE)
    when = models.DateTimeField(blank=True, null=True)
    location_id = models.ForeignKey(Location, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.show_id} - {self.when} - {self.location_id}"




class RepresentationUser(models.Model):
    representation_id = models.ForeignKey(Representation, blank=True, null=True, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, blank=True, null=True, on_delete=models.DO_NOTHING)
    places = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.representation_id} - {self.user_id} - {self.places}"
    
    def get_total_price(self):
        return self.places * self.representation_id.show_id.price



class Role(models.Model):
    role = models.CharField(max_length=30)

    def __str__(self):
        return self.role


class RoleUser(models.Model):
    role_id = models.ForeignKey(Role, blank=True, null=True, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)

# Commentaires des Users #

class Review(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    validate = models.BooleanField(default=False)

    def _str_(self):
        return "Review {self.id} for Show {self.show_id} by User {self.user_id}"
    

reservation/models/artist.py
from typing import Type
from django.db import models

class Artist(models.Model):
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)
    types = models.ManyToManyField(Type, through='ArtisteType')

    def __str__(self):
        return self.firstname + '' + self.lastname
    
    class meta: 
        db_table= "artists"

reservation/views/artist.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib import messages
import json
from django.conf import settings
from os.path import join

from reservation.models import Artist
from reservation.forms import ArtistDeleteForm, ArtistFormCreation

def allArtists(request):
    artists = Artist.objects.all()
    return render(request, "artist/allArtists.html", {'artists': artists})

def showArtist(request, artist_id):
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        raise Http404('Artiste inexistant')
    
    title = 'Fiche artiste'

    return render(request, 'artist/showArtist.html', {'artist' : artist, 'title' : title})

def artistCreate(request):
    if request.method == 'POST':
        form = ArtistFormCreation(request.POST)
        if form.is_valid():
            artist = form.save()
            # Load existing data
            with open(join(settings.BASE_DIR, 'reservation', 'fixtures', 'ArtistFixtures.json'), 'r') as f:
                data = json.load(f)
            # Add new artist
            data.append({
                "model": "reservation.artist",
                "pk": artist.pk,
                "fields": {
                    "firstname": artist.firstname,
                    "lastname": artist.lastname,
                }
            })
            # Save data back to file
            with open(join(settings.BASE_DIR, 'reservation', 'fixtures', 'ArtistFixtures.json'), 'w') as f:
                json.dump(data, f)
            return redirect('allArtists')
    else:
        form = ArtistFormCreation()
    title = "Creer un artiste"
    return render(request, 'artist/createArtist.html', {'form': form, 'title': title})




def editArtist(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)

    if request.method == 'POST':
        form = ArtistFormCreation(request.POST, instance=artist)
        if form.is_valid():
            form.save()
            messages.success(request, ("Artiste a bien ete modifier"))
            return redirect('showArtist', artist_id=artist.id)
    else:
        form = ArtistFormCreation(instance=artist)

    title = 'Modifier un artiste'

    return render(request, 'artist/editArtist.html', {
        'artist': artist,
        'form': form,
        'title': title
    })

def deleteArtist(request, artist_id):
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        raise Http404('Artist inexistant')

    if request.method == 'POST':
        form = ArtistDeleteForm(request.POST, instance=artist)
        if form.is_valid():
            # Load existing data
            with open(join(settings.BASE_DIR, 'reservation', 'fixtures', 'ArtistFixtures.json'), 'r') as f:
                data = json.load(f)

            # Filter out the deleted artist
            data = [item for item in data if item["pk"] != artist_id]

            # Save the data back to the file
            with open(join(settings.BASE_DIR, 'reservation', 'fixtures', 'ArtistFixtures.json'), 'w') as f:
                json.dump(data, f, indent=2)

            artist.delete()
            messages.success(request, ("Artiste a bien ete supprimer"))
            return redirect('allArtists')
    else:
        form = ArtistDeleteForm(instance=artist)

    title = 'Supprimer un artiste'

    return render(request, 'artist/deleteArtist.html', {
        'artist': artist,
        'form': form,
        'title': title
    })

reservation/views/show.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from reservation.forms import ShowRegistration
from django.contrib import messages
from django.core.paginator import Paginator

from reservation.models import Show


def displayShow(request, show_id):
    try:
        show = Show.objects.get(id=show_id)
    except Show.DoesNotExist:
        raise Http404('Pas de show identifier')

    title = 'Fiche d\'un show'
    return render(request, "show/show.html", {'show': show, 'title': title})

def addshow(request):
    if request.method == 'POST':
        fm = ShowRegistration(request.POST, request.FILES)
        if fm.is_valid():
            sl = fm.cleaned_data['slug']
            ti = fm.cleaned_data['title']
            des = fm.cleaned_data['description']
            pu = fm.cleaned_data['poster_url']
            li = fm.cleaned_data['location_id']
            bk = fm.cleaned_data['bookable']
            pr = fm.cleaned_data['price']
            reg = Show(slug=sl, title=ti, description=des,
                       poster_url=pu, location_id=li, bookable=bk, price=pr)
            if 'image' in request.FILES:
                reg.image = request.FILES['image']
            reg.save()
            fm = ShowRegistration()
    else:
        fm = ShowRegistration()
    return render(request, 'show/addshow.html', {'form': fm})




def editShow(request, show_id):
    show = get_object_or_404(Show, id=show_id)

    if request.method == 'POST':
        form = ShowRegistration(request.POST, instance=show)
        if form.is_valid():
            form.save()
            messages.success(request, ("Artiste a bien ete modifier"))
            return redirect('show_detail', show_id=show.id)
    else:
        form = ShowRegistration(instance=show)

    title = 'Modifier un show'

    return render(request, 'show/updateShow.html', {
        'show': show,
        'form': form,
        'title': title
    })

def allShows(request):
    # shows = Show.objects.all().order_by('?')
    shows_list = Show.objects.all()

    # Set up Pagination
    p = Paginator(Show.objects.all(), 3)
    page = request.GET.get('page')
    show = p.get_page(page)

    return render(request, "show/allShows.html", {'show_list': shows_list, "shows": show})

reservation/views/type.py
from django.shortcuts import render
from django.http import Http404

from models import Type


# Create your views here.
def show_all_type(request):
    types = Type.objects.all()

    title = 'Liste des types'

    return render(request, 'type/index.html', {
        'types': types,
        'title': title
    })


def showType(request, type_id):
    try:
        type = Type.objects.get(id=type_id)
    except Type.DoesNotExist:
        raise Http404('Type inexistant')

    title = 'Fiche d\'un type'

    return render(request, 'type/show.html', {
        'type': type,
        'title': title
    })

reservation/templates/show/addshow.html
{% extends "base.html" %}

{% block title %}NYGMA - Add Show{% endblock %}

{% block content %}
{% if user.is_superuser %}
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-lg-6 shadow p-8">
                <h3 class="text-center">Ajouter un nouveau spectacle</h3>
                <form action="" method=POST enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_slug">Slug</label>
                        <input type="text" class="form-control" id="id_slug" name="slug" placeholder="Entrez le slug" required>
                    </div>
                    <div class="form-group">
                        <label for="id_title">Titre</label>
                        <input type="text" class="form-control" id="id_title" name="title" placeholder="Entrez le titre" required>
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description</label>
                        <textarea class="form-control" id="id_description" name="description" placeholder="Entrez la description" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_poster_url">URL de l'affiche</label>
                        <input type="text" class="form-control" id="id_poster_url" name="poster_url" placeholder="Entrez l'URL de l'affiche" required>
                    </div>
                    <div class="form-group">
                        <label for="id_image">Ajouter une image</label>
                        <input type="file" class="form-control-file" id="id_image" name="image">
                    </div>
                    <div class="form-group">
                        <label for="id_location_id">Location</label>
                        <select class="form-control" id="id_location_id" name="location_id" required>
                            {% for loc in locs %}
                            <option value="{{ loc.id }}">{{ loc.designation }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="id_bookable" name="bookable">
                            <label class="form-check-label" for="id_bookable">Réservable</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_price">Prix</label>
                        <input type="number" class="form-control" id="id_price" name="price" placeholder="Entrez le prix" required>
                    </div>
                    <div class="form-group text-center">
                        <input type="submit" class="btn btn-success" value="Ajouter">
                    </div>
                </form>
        </div>
    </div>
</div>
{% else %}
<div class="p-4">
  <h1>Vous n'avez pas les droits pour accedez a la page</h1>
</div>
<div class="container p-3">
  <a class="btn btn-success" href="{% url 'login' %}">Login</a>
</div>
{% endif %}

{% endblock %}

reservation/templates/show/allShows.html
{% extends "base.html" %}

{% block content %}

<style>
    .custom-img {
        width: 100%;
        height: 200px;
        /* Ajustez la hauteur selon vos besoins */
        object-fit: cover;
    }
</style>


<div class="container">
    <div class="p-3">
        <form method="GET" action="">
            <select name="type">
                <option value="">--Select Type--</option>
                {% for type in types %}
                <option value="{{ type.id }}">{{ type.type }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Filter">
        </form>

        <h4 class="text-center alert alert-info">All Shows</h4>
    </div>
    <div class="d-flex justify-content-center">
        <nav aria-label="...">
            <ul class="pagination">
                {% if shows.has_previous %}
                <li>
                    <a class="page-link"
                        href="?page={{shows.previous_page_number}}{% if type %}&type={{ type }}{% endif %}"
                        tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                <li class="page-link">
                    page {{shows.number}} of {{shows.paginator.num_pages}}
                </li>
                {% if shows.has_next %}
                <li>
                    <a class="page-link"
                        href="?page={{shows.next_page_number}}{% if type %}&type={{ type }}{% endif %}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>


    </div>
    <div class="row p-3">
        {% for showd in shows %}
        <div class="card m-3 col-sm" style="width: 18rem;">
            {% if showd.image %}
            <img src="{{showd.image}}" class="card-img-top custom-img" alt="...">
            {% else %}
            <img src="{{showd.poster_url}}" class="card-img-top custom-img" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ showd.title }}</h5>
                <p class="card-text">{{ showd.description|truncatechars:200 }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Lieu : {{ showd.location_id }}</li>
                <li class="list-group-item">Prix: {{ showd.price }} Euro</li>
            </ul>
            <div class="card-body">
                <a href="/show/{{showd.id}}" class="card-link btn btn-info">Consulter</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center">
        <nav aria-label="...">
            <ul class="pagination">
                {% if shows.has_previous %}
                <li>
                    <a class="page-link"
                        href="?page={{shows.previous_page_number}}{% if type %}&type={{ type }}{% endif %}"
                        tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                <li class="page-link">
                    page {{shows.number}} of {{shows.paginator.num_pages}}
                </li>
                {% if shows.has_next %}
                <li>
                    <a class="page-link"
                        href="?page={{shows.next_page_number}}{% if type %}&type={{ type }}{% endif %}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>


    </div>
</div>

{% endblock %}

reservation/templates/show/createRepresentation.html
{% extends "base.html" %}

{% block title %}NYGMA - Add Show{% endblock %}

{% block extra_head %}
    <script>
        $(function() {
            $('.datetimepicker').datetimepicker({
                icons: {
                    time: 'fa fa-clock-o',
                    date: 'fa fa-calendar',
                    up: 'fa fa-chevron-up',
                    down: 'fa fa-chevron-down',
                    previous: 'fa fa-chevron-left',
                    next: 'fa fa-chevron-right',
                    today: 'fa fa-crosshairs',
                    clear: 'fa fa-trash',
                    close: 'fa fa-times'
                }
            });
        });
    </script>
{% endblock %}

{% block content %}
{% if user.is_superuser %}
<div class="container">
    <div class="row mt-5 mb-5 justify-content-center">
        <div class="col-lg-6 shadow p-8">
            <h3 class="text-center">Ajouter un Show</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                    <div class="input-group date datetimepicker" data-target-input="nearest">
                        {{ form.when }}
                        <div class="input-group-append" data-target=".datetimepicker" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Ajouter</button>
            </form>
        </div>
    </div>
</div>
{% else %}
<div class="p-4">
  <h1>Vous n'avez pas les droits pour accéder à la page</h1>
</div>
<div class="container p-3">
  <a class="btn btn-success" href="{% url 'login' %}">Login</a>
</div>
{% endif %}

{% endblock %}

reservation/templates/show/landing.html
{% extends "base.html" %}

{% block content %}

    <div class="container d-flex">
        <section>
            <div class="product">
                <div class="description">
                    <h3>{{ product.title }}</h3>
                    <h5>{{ location }}</h5>
                    <h5>{{ date }}</h5>
                    <h5>{{ product.get_display_price }} €</h5>
                    <h5>Quantité: {{ places }}</h5>
                    <h5>Prix total: {{ total }} €</h5>
                </div>
            </div>
            <button type="button" id="checkout-button">Payer</button>
        </section>
    </div>

    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
        var checkoutButton = document.getElementById("checkout-button");
        checkoutButton.addEventListener("click", function () {
            fetch("{% url 'create-checkout-session' %}", {
                method: "POST",
                headers: {
                    'X-CSRFToken': csrftoken
                }
            })
                .then(function (response) {
                    return response.json();
                })
                .then(function (session) {
                    console.log("Session ID:", session.id);
                    return stripe.redirectToCheckout({ sessionId: session.id });
                })
                .then(function (result) {
                    // If redirectToCheckout fails due to a browser or network
                    // error, you should display the localized error message to your
                    // customer using error.message.
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.error("Error:", error);
                });
        });
    </script>

{% endblock %}

reservation/templates/show/representationReserver.html
{% extends 'base.html' %}

{% block content %}
<div class="container ">
  <div class="m-5">
    <h2>Voici les representations disponibles</h2>
    <p>Nombre de représentations : {{ representationList|length }}</p>
  </div>
  <div class="list-group">
    {% for representation in representationList %}
    <a href="#" class="list-group-item list-group-item-action">
      <h4>{{ representation.show_id }}</h4>
      <h5>{{ representation.location_id }}</h5>
      <h6>{{ representation.when }}</h6>
      <h6>{{ representation.show_id.price }}eur</h6> 
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

reservation/templates/show/representationUserReservation.html
{% extends "base.html" %}

{% block title %}NYGMA - Réserver une représentation{% endblock %}

{% block content %}
<style>
  .container {
    max-width: 900px;
  }

  .shadow {
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .form-group label {
    font-weight: bold;
  }

  .btn {
    font-weight: bold;
  }

  .mt-4 {
    margin-top: 1.5rem;
  }

  .mt-5 {
    margin-top: 3rem;
  }

  .mb-5 {
    margin-bottom: 3rem;
  }

  .p-4 {
    padding: 1.5rem;
  }

  .p-3 {
    padding: 1rem;
  }

  .text-center {
    text-align: center;
  }

  .d-flex {
    display: flex;
  }

  .justify-content-center {
    justify-content: center;
  }
</style>

{% if user.is_authenticated %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 shadow p-4">
      <h3 class="text-center">Réserver une représentation</h3>
      <div class="mt-4">
        <p>Votre choix : <strong>{{ representation.show_id }}</strong></p>
        <p>Lieu : <strong>{{ representation.location_id }}</strong></p>
        <p>Ville : <strong>{{ representation.location_id.locality_id }}</strong></p>
        <p>Date : <strong>{{ representation.when }}</strong></p>
        <p>Prix : <strong><span id="totalPrice">{{ representation.show_id.price }}</span> eur</strong></p>
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group mt-4">
          <label for="id_places">Nombre(s) de place(s) désirée :</label>
          <input type="text" class="form-control" id="id_places" name="places" placeholder="Entrez le nombre de places" value="0" required>
        </div>
        <div class="form-group text-center mt-4">
          <div class="container">
            <div class="row">
              <input type="submit" class="btn btn-success col" value="Réserver">
              <p class="col"><strong>Total: <span id="totalAmount"></span> eur</strong></p>
            </div>
          </div>
        </div>
      </form>
      <div class="text-left">
        <a href="{% url 'show_detail' representation.show_id.id %}" class="btn btn-primary btn-warning">Retour</a>
    </div>		
    </div>
  </div>
</div>

<script>
  document.getElementById('id_places').addEventListener('input', function() {
    var places = this.value.trim() !== '' ? parseInt(this.value) : 0;
    var price = parseFloat(document.getElementById('totalPrice').textContent);
    var total = places * price;
    document.getElementById('totalAmount').textContent = total.toFixed(2);
  });

  // Set initial total amount to 0
  document.getElementById('totalAmount').textContent = '0.00';
</script>

{% else %}
<div class="container p-4">
  <h1 class="text-center">Veuillez d'abord vous connecter</h1>
</div>
<div class="container p-3 d-flex justify-content-center">
  <a class="btn btn-success" href="{% url 'login' %}">Se connecter</a>
</div>
{% endif %}

{% endblock %}

reservation/templates/show/show.html
{% extends "base.html" %}

{% if messages %}
<div class="alert alert-info">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

{% block content %}
<div class="container m-5">
  <div class="row">
    <div class="col-10">
      <div class="card">
        {% if show.image %}
        <img src="../{{ show.image }}" class="card-img-top" alt="...">
        {% else %}
        <img src="{{ show.poster_url }}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
          <h3 class="card-title">{{ show.title }}</h3>
          <p class="card-text">{{ show.description }}</p>
          <p class="card-text"><strong>Prix:</strong> {{ show.price }} EUR</p>
          {% if not user.is_authenticated %}
          <a href="{% url 'login' %}" class="btn btn-info">Se connecter</a>
          {% endif %}
          {% if user.is_superuser %}
          <a href="{{ show.id }}/editt" class="btn btn-info">Modifie</a>
          {% endif %}
          <hr/>
          <h4>Commentaire:</h4>
          {% for review in show.review_set.all %}
            <div class="review">
              <h4>{{ review.user.username }}</h4>
              <p>{{ review.comment }}</p>
              <p><strong>Étoiles:</strong> {{ review.stars }}</p>
            </div>
          {% empty %}
            <p>Aucun commentaire pour le moment</p>
          {% endfor %}
          {% if user.is_authenticated %}
            <h4>Mettre un commentaire:</h4>
            <form method="POST" action="{% url 'create_review' show.id %}">
              {% csrf_token %}
              <textarea name="comment" placeholder="Ici votre commentaire" required></textarea>
              <input type="number" name="stars" min="1" max="5" placeholder="etoile (1-5)" required>
              <input type="submit" value="Submit">
            </form>
          {% endif %}
        </div>
      </div>
    </div>
    
{% endblock %}